### ISSUE TITLE
`optional.js` is empty with no arguments and documentation

### ISSUE THREAD

**Issue by Rubix982** [convergencelabs/javascript-examples#24]
The `src/optional.js` is empty (0 bytes). Should there be anything here?

**Comment by mmacfadden** [comment]
Greetings.  In the title of the issue you mention "optional.js", but in the description you mention "config.js".  Which file are you asking about?

**Comment by Rubix982** [comment]
Really sorry about the typo. Fixed. This issue is about `optional.js`.

**Comment by mmacfadden** [comment]
Ok, yes. This file is supposed to be empty.

**Comment by Rubix982** [comment]
Noted. Closing.
